default:
    tags:
        - sidha

workflow:
    rules:
        - if: $CI_COMMIT_TAG
          when: never
        - if: $CI_COMMIT_BRANCH == 'master'

before_script:
    - docker info
    - javac -version

variables:
    IMAGE_OPENJDK_GRADLE: gradle:7.3.3-jdk17-alpine
    IMAGE_DOCKER_DIND: docker:20.10.16

stages:
    - build
    - deploy

build:
    image: $IMAGE_OPENJDK_GRADLE
    stage: build
    only:
        - master
    script:
        - echo "Compiling the code..."
        - cd $CI_PROJECT_DIR
        - sh gradlew clean assemble
    artifacts:
        paths:
            - build/libs/api-0.0.1-SNAPSHOT.jar

deploy:
    stage: deploy
    only:
        - master
    before_script:
        - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
        - eval $(ssh-agent -s)
        - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

    script:
        - echo "Deploy to server..."
        - ssh "${DEPLOY_USERNAME}@${DEPLOY_SERVER}" "cd sidha-backend"
        - ssh "${DEPLOY_USERNAME}@${DEPLOY_SERVER}" "sudo docker-compose down"
        - ssh "${DEPLOY_USERNAME}@${DEPLOY_SERVER}" "git checkout master"
        - ssh "${DEPLOY_USERNAME}@${DEPLOY_SERVER}" "git pull origin master"
        - ssh "${DEPLOY_USERNAME}@${DEPLOY_SERVER}" "sudo docker-compose up --build"