version: '3.3'
services:
  web_be:
    container_name: web_be
    build: 
      context: .
    restart: always
    ports:
      - "10001:8080"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
      - /home/devinahaz/filedata:/home/devinahaz/filedata
      - /home/devinahaz/imagedata:/home/devinahaz/imagedata
    depends_on:
      - db
    platform: linux/amd64
    environment:
      - TZ=Asia/Jakarta
  db:
    image: postgres:14-alpine
    ports:
      - '15001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=admin-sidha
      - POSTGRES_PASSWORD=propenzjaya-d01
      - TZ=Asia/Jakarta
    volumes:
      - db:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"  # Map HTTP port 80 on the host to port 80 in the Nginx container
      - "443:443"  # Map HTTPS port 443 on the host to port 443 in the Nginx container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx configuration file
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web_be
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email devinahaz@gmail.com -d sidha-backend.site --agree-tos

volumes:
  db:
    driver: local
