version: '3.3'
services:
  web:
    build: 
      context: .
    restart: always
    ports:
      - "10001:8080"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    depends_on:
      - db
    networks:
      - backend-network
    platform: linux/amd64
  db:
    image: postgres:14-alpine
    ports:
      - '15001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=admin-sidha
      - POSTGRES_PASSWORD=propenzjaya-d01
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - backend-network
volumes:
  db:
    driver: local
networks:
  backend-network:
    driver: bridge  
